on: [push]

jobs:
  run_tests:

    runs-on: windows-2022
            
    steps:
      - name: Unity - Test runner
        uses: game-ci/unity-test-runner@v4.1.1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
