on: [push]

jobs:
  run_tests:
    environment: main
    projectPath: .
    runs-on: ubuntu-latest  
    steps:
      - name: Unity - Test runner
        uses: game-ci/unity-test-runner@v4.1.1
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
